version: '3'

services:
  dbiapp:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    restart: always
    volumes:
      - .:/code
    #ports:
    #  - "8081:8081"
    #expose:
    #  # Opens port 8081 on the container
    #  - '8081'
    networks:
      - dbintegration-compose-network
    env_file:
      - .env.dev


networks:
  dbintegration-compose-network:
    driver: bridge
