version: '3'

services:
  dbiapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: dotnet run --project /code/src/WebApp/
    restart: always
    volumes:
      - ./app:/code
    ports:
      - "5000:5000"
      - "5001:5001"
    expose:
      - '5000'
      - '5001'
    networks:
      - dbintegration-compose-network
    env_file:
      - ./conf/.env.dev

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "<senha>"
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - dbintegration-compose-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@local.org"
      PGADMIN_DEFAULT_PASSWORD: "SPg@Dpr4!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - dbintegration-compose-network

networks:
  dbintegration-compose-network:
    driver: bridge
