version: '3'

services:
  dbiapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: dotnet run --project /code/src/WebApp/
    restart: always
    volumes:
      - ./app:/code
    ports:
      - "5000:5000"
      - "5001:5001"
    expose:
      - "5000"
      - "5001"
    networks:
      - dbintegration-compose-network


networks:
  dbintegration-compose-network:
    driver: bridge
