version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "<senha>"
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - dbintegration-compose-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@local.org"
      PGADMIN_DEFAULT_PASSWORD: "SPg@Dpr4!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - dbintegration-compose-network

networks:
  dbintegration-compose-network:
    driver: bridge
